### ISSUE TITLE
Allow evaluating branches other than master

### ISSUE THREAD

**Issue by atkinsonm** [codeinspectorio/citool#2]
As discussed in #1, the analysis only works in the master branch. This feature request is for supporting evaluation from other branches.

**Comment by juli1** [comment]
This one will definitively be more difficult and long since the engine takes the master branch and the user does not specify the branch when specifying the repository. This change requires work on the engine and product itself. Not saying this will not happen but it needs more thinking and scoping to make it happen. But this is the kind of use-case we like to hear and we are thankful to have such requests :-)

**Comment by atkinsonm** [comment]
Thanks. Not to add complexity but to further specify the use case: I may have many short-lived branches. I might even have multiple branches attempting to call `code-inspector` simultaneously. The purpose would be to catch code regression in feature branches before merging to master which represents production.

**Comment by juli1** [comment]
It seems definitively something to work on the platform and not only in the cli tool. Can you reach out to us through https://www.code-inspector.com/contact so that we can discuss about use-case and specific needs. The discussion probably needs to happen outside this github thread.

**Comment by juli1** [comment]
@atkinsonm we are now supporting the feature you asked. This is now implement in our new tool and let you compare one branch of your code with another branch. Or another repository. Look at the documentation on https://github.com/codeinspectorio/citool

If you need to have more details and help to use this feature and how to use the platform, do not hesitate to contact us on  https://www.code-inspector.com/contact

**Comment by juli1** [comment]
Closing the issue since the feature is now being implemented. pypi packages will be updated in the next days.

**Comment by atkinsonm** [comment]
Thank you @juli1! I finally got around to using this and it works great! The only undocumented "feature" I found is that `code-inspector-analyze` seems to disregard the case of the project name but `code-inspector-compare` regards the project name as case-sensitive.

Excellent work! Does exactly what I was looking for.

**Comment by atkinsonm** [comment]
In case you're interested I've updated my project to handle integration of codeinspector into a GitLab CI pipeline to support comparison of branches: https://gitlab.com/jhctechnology/code-quality/code-inspector

**Comment by juli1** [comment]
I am very interested :-) can I contact you in private about it?

Thanks!

**Comment by atkinsonm** [comment]
Absolutely, my email is in my profile
